apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
                service:
                  name: server-srv
                  port:
                    number: 3000
          - path: /
            pathType: Prefix
            backend:
                service:
                  name: client-srv
                  port:
                    number: 5000
