apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: chihweidavidliu/blabber-server
          envFrom:
          - configMapRef:
              name: config
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server
  type: ClusterIP
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
